name: hello_notes
description: hackathon project
version: 0.0.1
author: Nick Anderssohn <ncadevelopment@gmail.com>
environment:
  sdk: any
dependencies:
  browser: any
  js: any
  sass: any
  image: any
  simple_streams: any
transformers:
- $dart2js:
    minify: true
- sass
